version: "3.8"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
  maintenance:
    image: shyim/shopware:latest
    depends_on:
      - mysql
    env_file:
      - .env
    command: ['maintenance']
    volumes:
      - state:/state
      - plugins:/var/www/html/custom/plugins
      - files:/var/www/html/files
      - jwt:/var/www/html/config/jwt
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - bundles:/var/www/html/public/bundles
      - sitemap:/var/www/html/public/sitemap
  shopware:
    image: shyim/shopware:latest
    command: ['web']
    depends_on:
      - maintenance
    env_file:
      - .env
    environment:
      DISABLE_ADMIN_WORKER: 'true'
    ports:
      - 80:80
    volumes:
      - plugins:/var/www/html/custom/plugins
      - files:/var/www/html/files
      - jwt:/var/www/html/config/jwt
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - bundles:/var/www/html/public/bundles
      - sitemap:/var/www/html/public/sitemap
  worker:
    image: shyim/shopware:latest
    restart: always
    depends_on:
      - shopware
    env_file:
      - .env
    command: ['cli', 'messenger:consume', '--memory-limit=1G', '--time-limit=60']
    volumes:
      - plugins:/var/www/html/custom/plugins
      - files:/var/www/html/files
      - jwt:/var/www/html/config/jwt
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - bundles:/var/www/html/public/bundles
      - sitemap:/var/www/html/public/sitemap
  task:
    image: shyim/shopware:latest
    restart: always
    depends_on:
      - shopware
    env_file:
      - .env
    command: ['cli', 'scheduled-task:run', '--memory-limit=1G', '--time-limit=60']
    volumes:
      - plugins:/var/www/html/custom/plugins
      - files:/var/www/html/files
      - jwt:/var/www/html/config/jwt
      - theme:/var/www/html/public/theme
      - media:/var/www/html/public/media
      - thumbnail:/var/www/html/public/thumbnail
      - bundles:/var/www/html/public/bundles
      - sitemap:/var/www/html/public/sitemap
volumes:
  state:
  mysql-data:
  plugins:
  files:
  jwt:
  theme:
  media:
  thumbnail:
  bundles:
  sitemap: